AllCops:
  TargetRubyVersion: 3.1
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'lib/puma-redeploy.rb'

plugins:
  - rubocop-rake
  - rubocop-performance
  - rubocop-rspec
  - rubocop-thread_safety

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']

Metrics/MethodLength:
  Max: 30

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 12

RSpec/ExampleLength:
  Max: 6

RSpec/ExpectInHook:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

# Need to look into this one
ThreadSafety/DirChdir:
  Enabled: false
